apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  app.kubernetes.io/version: v0.31.1
  catalog.kubestack.com/heritage: kubestack.com/catalog/prometheus
  catalog.kubestack.com/variant: base
commonLabels:
  app.kubernetes.io/component: operator
  app.kubernetes.io/managed-by: kubestack
  app.kubernetes.io/name: prometheus
resources:
- bundle.yaml
